name: apply-issue-template-when-empty

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Apply template if issue body is empty
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = (context.payload.issue.body || '').trim();
            if (body.length > 0) {
              core.info('Issue body is not empty. Skipping.');
              return;
            }
            const templatePath = '.github/ISSUE_TEMPLATE/task.md';
            if (!fs.existsSync(templatePath)) {
              core.setFailed(`Template not found at ${templatePath}`);
              return;
            }
            const template = fs.readFileSync(templatePath, 'utf8');
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: template
            });
            core.info('Applied task.md template to empty issue body.'); 